title:            "喃言梦语"  
description:      "不喧哗 自有声"
url:              "http://movyery.me"  
signoff:          "林淼渺"

# About/contact
owner: 
  name:           "林淼渺"
  email:          movyery@sina.com 

links:
  - name:         Blog
    url:          /
  - name:         Themes
    url:          /themes
    external:     true
  - name:         Tags
    url:          /tags
    external:     true
  - name:         Tools
    url:          /tools
    external:     true
  - name:         About
    url:          /about
    external:     true
  - name:         Rss
    url:          /feed.xml
    external:     true

highlighter:      rouge

markdown:         kramdown
kramdown:
  input:          GFM



gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink:        none
paginate:         8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:         Asia/Shanghai




disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.
